### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by invisiblecoder99** [tianxiangbing/chat#1]
Warning: missing space before text for line 5 of jade file "/root/chat/views/index.jade"
GET / 304 229.251 ms - -
GET /stylesheets/style.css 304 2.509 ms - -
GET /javascripts/jquery-1.11.2.js 304 1.279 ms - -
GET /javascripts/socket.io.js 304 1.169 ms - -
GET /javascripts/chat.js 304 0.901 ms - -
GET /javascripts/draw.js 304 0.517 ms - -
select * from chatmsg  where uname="gvgvg" or `to` =""  or `to` is null or `to`="gvgvg" order by time desc limit 0,20 
GET /socket.io/?EIO=3&transport=polling&t=1530635674175-0 404 35.832 ms - 1696
GET /stylesheets/pen.png 304 36.176 ms - -
err:Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
undefined
GET /getmsg?name=gvgvg 200 51.547 ms - 2
GET /socket.io/?EIO=3&transport=polling&t=1530635676001-1 404 19.515 ms - 1696
GET /socket.io/?EIO=3&transport=polling&t=1530635679754-2 404 31.827 ms - 1696
GET /socket.io/?EIO=3&transport=polling&t=1530635682831-3 404 17.425 ms - 1696
GET /socket.io/?EIO=3&transport=polling&t=1530635688326-4 404 17.838 ms - 1696
GET /socket.io/?EIO=3&transport=polling&t=1530635693629-5 404 25.535 ms - 1696
G

**Comment by tianxiangbing** [comment]
这些错误只是连接数据库报错了，由于我用的是免费数据空间，可能已经过期无法使用了

**Comment by invisiblecoder99** [comment]
can you give database file @tianxiangbing  you did miss that and your code have errors that cannot connect database
